# -*- coding: utf-8 -*-
"""ClstFuzzy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eP4_t53v3CYgbeAkiD5a4tVnrM7HTim-
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install fuzzy_c_means 
import numpy as np 
import pandas as pd
import matplotlib .pyplot as plt 
# %matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from fcmeans import FCM
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from fcmeans import FCM
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

data = pd.read_csv('/content/sample_data/test.csv')

data.shape

columns = data.columns
columns

data = data.values
data

fcmModel = FCM(n_clusters=80)

fcmModel.fit(data)

center = fcmModel.centers

center

pred = fcmModel.predict(data)

pred.shape

pred

df = pd.DataFrame(data, columns = columns)

df

df['Cluster'] = pred

df

df['Cluster'].value_counts()

df.to_csv("PM_fuzzy_clstrs80.csv", index=False)

